# Generated by Django 2.2.4 on 2019-08-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190827_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='firstValue',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.DecimalField(decimal_places=3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='secondValue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
