# Generated by Django 2.2.4 on 2018-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20190827_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='firstValue',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='result',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='secondValue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True),
        ),
    ]
